### ISSUE TITLE
Problem with init_settings.lua

### ISSUE THREAD

**Issue by AntonHorai** [bondrogeen/DoT#14]
Got only this message after restart in ESPlorer v0.2.0:
NodeMCU 0.9.5 build 20150318  powered by Lua 5.1.4
1
lua: init_settings.lua:1: attempt to index global 'sjson' (a nil value)

UPD:
Uploaded uncompressed file src\lua\init_settings
Error occured on string 11: "lua: init_settings.lua:11: attempt to index global 'sjson' (a nil value)".

**Comment by bondrogeen** [comment]
Not installed SJSON Module
https://nodemcu.readthedocs.io/en/master/en/modules/sjson/

Build your firmware with SJSON

**Comment by AntonHorai** [comment]
Works well after flashing DoT-master build with NodeMCU-PyFlasher-4.0-x86. Flashing with NodeMCU Flasher didnt work on any settings.

**Comment by bondrogeen** [comment]
I have no problems with the firmware via NodeMCU Flasher

> lua: init_settings.lua:1: attempt to index global '**sjson**' (a **nil** value)

According to your log, you did not have SJSON
